Update slider js
VolhaVaitulevich/Online-Zoo pull request #3
Opened 2022-11-22 11:33 UTC by VolhaVaitulevich

1. Added background images;
2. Updated slider with js;

2022-11-22 16:08 UTC, siarhei-papkou requested changes

2022-11-22 16:08 UTC, siarhei-papkou commented on pages/main/index.js
> +window.onload = function () {
document.addEventListener('DOMContentLoaded', function () {

2022-11-22 16:08 UTC, siarhei-papkou commented on pages/main/index.js
> +    if (slides.dataset.transition === null) {
ternary?

2022-11-23 08:53 UTC, VolhaVaitulevich commented on pages/main/index.js
> +window.onload = function () {
Updated in a new commit

2022-11-23 08:53 UTC, VolhaVaitulevich commented on pages/main/index.js
> +    if (slides.dataset.transition === null) {
Updated to ternary in a new commit

2022-11-23 08:53 UTC, VolhaVaitulevich commented on pages/main/index.js
> +  for (let i = 0; i < slideShows.length; i += 1) {
Changed to forEach =)

2022-11-23 19:40 UTC, VolhaVaitulevich commented on pages/main/index.js
> +    const slidesWidth = slides.clientWidth;
Added an event listener for the resize event that triggers a page reload, but I'm not sure if that's how it's supposed to work.

2022-11-23 20:48 UTC, VolhaVaitulevich commented on pages/main/index.js
> +    const slidesWidth = slides.clientWidth;
Updated one more time so that it works without reloading the page after resize

2022-11-26 17:30 UTC, merged